# Prediction of house prices according to the town and area

In [6]:
import pandas as pd
import numpy as np
import sklearn.linear_model as lm

In [7]:
df = pd.read_csv('data/homeprices_city.csv')

In [8]:
dummies=pd.get_dummies(df.town)

In [9]:
merged= pd.concat([df,dummies],axis='columns')

In [10]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [11]:
final =merged.drop(['town','west windsor'],axis='columns')

In [12]:
reg =lm.LinearRegression()


In [13]:
X = final.drop(['price'],axis='columns')
y = final['price']


In [14]:
reg.fit(X,final['price'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
reg.predict([[2800,0,1]])

array([590775.63964739])

In [16]:
reg.predict([[3400,0,0]])

array([681241.66845839])

In [17]:
reg.score(X,y)

0.9573929037221873

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
dfle=df
dfle.town=le.fit_transform(dfle.town)

In [20]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [21]:
X = dfle[['town','area']].values
X


array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [22]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [23]:
from sklearn.preprocessing import OneHotEncoder 
ohe =OneHotEncoder(categorical_features=[0])


In [24]:
X=ohe.fit_transform(X).toarray()

/home/satyam/.conda/envs/tensorflow/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/satyam/.conda/envs/tensorflow/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [25]:
X = X[:,1:]
len(X)

13

In [26]:
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [27]:
reg.predict([[1,0,2800]])

array([590775.63964739])

In [28]:
reg.predict([[0,1,3400]])

array([681241.6684584])