In [43]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle # for storing and importing the trained model
from sklearn.externals import joblib # for importing and storing the trained model

In [44]:
df= pd.read_csv('data/homeprices_with_rooms.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [45]:
median_bedrooms=df.bedrooms.median()

In [46]:
df['bedrooms']=df.bedrooms.fillna(median_bedrooms)

In [47]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [48]:
reg.predict([[1000,4,1]])

array([423709.24621066])

In [49]:
reg # Trained model with the given data to predict the prices

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

## Saving trained model  

In [50]:
with open('data/model_pickle','wb') as f:
    pickle.dump(reg,f)

In [51]:
with open('data/model_pickle','rb') as f:
    mp=pickle.load(f)
    

In [52]:
mp.predict([[10,1,2]])

array([239369.0705455])

In [53]:
joblib.dump(reg,'data/model_joblib')

['data/model_joblib']

In [54]:
MJ = joblib.load('data/model_joblib')

In [42]:
MJ.predict([[10,2,4]])

array([256294.51480617])